### ISSUE TITLE
Amplication Data Service Generator: RBAC does not seem to be properly implemented

### ISSUE THREAD

**Issue by rburgst** [amplication/amplication#1132]
**Describe the bug**
When I create a new application (today) and the generated app already contains a user entity. I would expect that one user cannot read the info about another.

**To Reproduce**
1. generate an application with the default user entity
2. start the server
3. create a 2nd user
4. query the REST endpoint `/api/users`
5. query the REST endpoint `/api/users/<id-of-user2>` with authentication of `admin`
6. query the REST endpoint `/api/users/<id-of-admin-user>` with authentication of `newuser`

**Expected behavior**
It should not be possible to 
a) dump all users 
b) read info about other users (except for admin users maybe)

**Screenshots**
N/A

**Additional context**

On that note I try to figure out how RBAC is supposed to work. How is decided whether an entity is "owned" by the currently logged in user?

**Comment by yuval-hazaz** [comment]
hi @rburgst 
The app generated by Amplication isa "single-tenant" application by design, 
A user with the relevant role and access permissions for an entity can access all the data in the entity. 
So, if you didn't change the default permissions on the "user" entity, all user can create, update, and delete users.

What you are referring to, is a multi-tenant permission schema, which was already requested by other community members
you can track the issue here #875

Please add your comment and some use cases so we make sure a future implementation will answer the actual requirements

**Comment by yuval-hazaz** [comment]
duplicate #875

**Comment by rburgst** [comment]
@yuval-hazaz thanks for the rapid feedback. The question still remains, how can I implement specific authorization rules so that e.g. a user can view all photos but only edit the ones that he himself has created.
While this is definitely related to #875, I think this is clearly not "multi tenant".

**Comment by yuval-hazaz** [comment]
At this stage, this is the kind of logic you need to implement with a code. 
hopefully as we move forward with the project we will add more features of this kind out of the box.

**Comment by rburgst** [comment]
in order to facilitate that, it would be nice to be able to also have references to the creator and update user in the default audit fields per entity (as we already have the creation and update timestamp).

**Comment by yuval-hazaz** [comment]
reopening for reference

**Comment by yuval-hazaz** [comment]
Documented as a new feature request #1147
