### ISSUE TITLE
Client: One to many field has 400 graphql error in admin ui when not searchable

### ISSUE THREAD

**Issue by twavis** [amplication/amplication#1384]
One to many field errors out in admin ui

**To Reproduce**
1. Create new sample app
2. Create a new Address and Customer linked to that address
3. View the created address
4. See error in network log

**Comment by yuval-hazaz** [comment]
Thanks
I can confirm - when the related field is not set as "searchable, the API is blocking queries that search by the related field. - this is expected behavior. 

but - we need to fix a couple of things:
1. update the sample app to set the fields as "searchable' by default for a better experience.
2. update the admin UI not to include the list view if the field is not "searchable"
