### ISSUE TITLE
Amplication Server - Entity Version Resolver Coverage 

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#1810]
Improve entity service tests coverage and add new tests.

Service path: `./packages/amplication-server/src/core/entity/entity.version.resolver.ts`

We use `jest` for tests and `jest-mock-extended` for mocking.

**Comment by g-traub** [comment]
Can I work on this ?

**Comment by mshidlov** [comment]
@g-traub Yes sure 👍 , I`m assigning you :)

**Comment by g-traub** [comment]
Actually, after having a look, there isn't much I can do 

The 3 resolvers in `entityVersion.resolver.ts` are tested in `entity.resolver.ts`. 

The coverage is : *86.95 | 100 | 62.5 | 85.71* and I don't see how to improve it.

It doesn't make sense to have a separated test file, since we would need to use entity resolvers anyway (for entity and versions).

`entityVersion.resolver.ts` could even be merged with `entity.resolver.ts` IMO, but it's out of the scope of this issue

What do you think? :)

**Comment by yuval-hazaz** [comment]
thanks
I will close this one
