### ISSUE TITLE
🐛 Bug Report: admin ui test fail

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#1893]
### 📜 Description

if you generate app and run in the admin ui test it fail because it dont have any tests

### 👟 Reproduction steps

run npm test in the admin-ui folder

### 👍 Expected behavior

work

### 👎 Actual Behavior

fail

### 💻 Device

Desktop

### 💻 Operating system

MacOS

### 🌍 Browser

Firefox

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by jainpawan21** [comment]
For this issue, we should write admin UI tests?

**Comment by tupe12334** [comment]
@jainpawan21 We ether write some test or add `SKIP_PREFLIGHT_CHECK=true` to the env file

**Comment by jainpawan21** [comment]
`SKIP_PREFLIGHT_CHECK=true` should be added in root env file or dsg package env file

**Comment by tupe12334** [comment]
@jainpawan21 To the `/packages/amplication-data-service-generator/src/admin/create-dotenv.template.env` file

**Comment by jainpawan21** [comment]
Thanks, Can you please assign this to me?

**Comment by tupe12334** [comment]
@jainpawan21 You been assign, good luck!

**Comment by yuval-hazaz** [comment]
@tupe12334 sorry for jumping on this a little too late, but I am not sure it is the right thing to add this flag to the .env file

what is the impact of this flag? what will happen if users will want to run tests on the admin-ui? 
where it is failing with it?

**Comment by yuval-hazaz** [comment]
@mshidlov please review also

**Comment by mshidlov** [comment]
@yuval-hazaz I agree this flag is a patch for failing `npm run tests` command in the Admin-UI.

The tests are failing because there aren't any tests. this behavior is not a bad thing and silencing failing errors most of the time is not the best way. if a developer is choosing to silence the error by itself this is his choice. 

Adding this flag may create confusion as failing tests are silenced and if a developer will add tests in the future, he can miss the fact that there is an environment that is set to skip those tests.
