### ISSUE TITLE
🐛 Bug Report: can not create the same gitOrganization in two different workspace  

### ISSUE THREAD

**Issue by morhag90** [amplication/amplication#2823]
### What happened?

can not create gitOrganization that already installed in another workspace 

### What you expected to happen

gitOrganization will be successfully created

### How to reproduce

1. create two workspaces 
2. create new app in workspace A
3. create new app in workspace B
4. in app workspace A => goto sync with Github page => install Github app in organization 
5. goto Github and delete this installation
6. goto  app in workspace B =>  goto sync with Github page => install Github app in the same organization from step 4 
7. the organization will not display in gitOrganization list (because this organization already exist in gitOrganization table) 

**need to successfully create the gitOrganization in the second workspace**

### Amplication version

0.13.0

### Environment

Node version: v16.14.2
npm version: 8.5.0 
Docker version:  20.10.12, build e91ed57
Cloud provider: AWS

**Comment by yuval-hazaz** [comment]
@morhag90 as we discussed this happen because we have a unique key on the table for gitProvider + gitOrganization

so our options are:
1. remove the unique key
2. Show the user on workspace B a descriptive error that will allow them to understand the cause
3. Automatically remove the gitOrganization record when the app is removed from GitHub
4. Let the user delete a gitOrganization from a workspace 

my opinion is that we first remove the unique key - it does not serve any logical use case. 
The problem starts because we are not deleting the record when the app is removed from GitHub, but still if the user got to the point that they removed the app and they are trying to install it on a new workspace that should work. 

also, we should add a screen where we allow the user to manage the git connections - I will create a separate feature request for that. In this page, they will be able to remove installations manually. 

I will also open another feature request to automatically remove the GitOrganziation record when the app is removed from the provider
