### ISSUE TITLE
🐛 Bug Report: Left nav - Container wrong padding

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3485]
### What happened?

We need to have a 16px padding between the top nav and left.

Bad
![image](https://user-images.githubusercontent.com/96179897/185074271-db52c970-22e9-471d-b19d-612198a4c38d.png)

Good
![image](https://user-images.githubusercontent.com/96179897/185074351-a61a56b9-bfee-415d-8327-5286249fbfd9.png)

### What you expected to happen

Adding 16px padding between the top nav and the left.

### How to reproduce

Everywhere in the app where we have a left-side nav.

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by KlausMikhaelson** [comment]
Hello @alexbass86 is someone working on this ? if not than can I get it assigned to me ?

**Comment by tupe12334** [comment]
@KlausMikhaelson Yes of course! I will assign you.

**Comment by KlausMikhaelson** [comment]
Hey @tupe12334 
<img width="725" alt="image" src="https://user-images.githubusercontent.com/100528412/185219788-2d19ef59-bc39-46ae-9531-a04663d75416.png">
Ig this is the page that the padding needs to be fixed in but I can't see any top border that we were supposed to add padding from so can you please help me out here ?
