### ISSUE TITLE
🐛 Bug Report: minor UI issues related to text box

### ISSUE THREAD

**Issue by Shubhdeep12** [amplication/amplication#3520]
### What happened?

Some UI issues:
1. Across the platform the text input are not having max limit.
2. Word break needs to applied at the Roles name as it can cause UI issue.
3. text input for passwords are normal text input instead it should be in a bullet dots pattern with option to view or hide for example in database settings.

### What you expected to happen

All the above points should be taken care as mentioned above.

### How to reproduce

![image](https://user-images.githubusercontent.com/43654389/185672804-18e3612b-7d0b-44db-92cf-9595f8bf1460.png)

![image](https://user-images.githubusercontent.com/43654389/185672899-0639bd0d-7dc2-4c64-9489-3fa9f87b6af2.png)

### Amplication version

0.14.12

**Comment by Himanxu1** [comment]
I want to work on this issue . Need some help while resolving it

**Comment by barshimi** [comment]
how can I help you @Himanxu1 ?

**Comment by Himanxu1** [comment]
How can I find the code related to this issue .
Assign this issue to me !

**Comment by yuval-hazaz** [comment]
Thanks for reporting this. see my comments about the issues listed above:
1. What kind of limit do you want to use? each field may have a different length limit depends on the DB schema and I don't think it is worth adding specific value on each field as the limits are virtual and in most cases they will not impact the user in any case.
2. for better UX I think we should use ellipsis with a tooltip with the full name. 
3. this password will appear in clear text in the generated code (as it stated in the description in the page) and we do not want to use a password field in order not to let the user think otherwise. This should not be used for any secret - it should be the default dev password.


So, 1 & 3 should not be changed. 

you can work on 2.

**Comment by yuval-hazaz** [comment]
@Himanxu1 I assigned the issue to you. 
The code is in this folder 
https://github.com/amplication/amplication/tree/master/packages/amplication-client/src/Roles

Let us know if you can move forward.

**Comment by Himanxu1** [comment]
Thanks for assigning me .

**Comment by yuval-hazaz** [comment]
already fixed
