### ISSUE TITLE
Outdated images in the "run your app on development environment" section

### ISSUE THREAD

**Issue by KlausMikhaelson** [amplication/amplication#3592]
### Describe the issue with documentation

So as per the docs we should be able to see a download button after the generate code in the left section (which is now updated to be in right side)
<img width="960" alt="amplication new bug" src="https://user-images.githubusercontent.com/100528412/186685370-d5d2361f-f8b2-4bcf-8ccc-8be30da2c142.png">
like this but currently it looks like this
<img width="960" alt="amplication new bug2" src="https://user-images.githubusercontent.com/100528412/186685437-cf4de947-4a5b-4fad-be8b-f4d04d8a91af.png">
and even I wasn't able to find the download button anywhere so if anyone can point that out than it will be great

### How to solve the problem

Update the images and improve the UI

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
Thanks for reporting this.
We deployed a new UI and some new features the day before yesterday and are working on updating the docs. It is a rolling plan and is already in progress. 

@MoFoGo  please make sure we include this in the new docs. 

@KlausMikhaelson, we are aiming to get all users to use GitHub instead of downloading the code since using Github we can provide much more value. The download option is limiting our ability to extend the functionality on code sync and more advanced architectures. 

Is there any reason you prefer to download the code instead of pushing the code to a GitHub repo?

**Comment by KlausMikhaelson** [comment]
Okay @yuval-hazaz These  updates sounds really good and ig it will be much better this way I am sure if I am not wrong than the code will be directly pushed to a repository that the user has to create and add there ig right ?

**Comment by yuval-hazaz** [comment]
exactly

**Comment by KlausMikhaelson** [comment]
That'll be really awesome !, thank you for the response so should I close this issue ?

**Comment by yuval-hazaz** [comment]
Let's leave it to @MoFoGo to decide whether to close or not. Depends on how he tracks the progress of the overall task.

**Comment by KlausMikhaelson** [comment]
Okay got it !
