### ISSUE TITLE
🐛 Bug Report: New project commits page totally broken after building

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3710]
### What happened?

When building a new project (that has no resources), after hitting Build, the Commits page is totally broken. No build actually happens.

![Screenshot 2022-09-04 at 16 33 32](https://user-images.githubusercontent.com/4976416/188319106-b87c6570-d702-4802-ad72-d759b0f82255.png)

### What you expected to happen

Either something preventing me from building if it's not the right time (maybe I need a resource), or a better error message/use friendly message.

### How to reproduce

1. Create a new project
2. Hit "Commit & Build"
3. Navigate to the specific commit's page

### Amplication version

0.15.3

**Comment by abrl91** [comment]
This issue was fixed by #3761 

@yuval-hazaz this issue happens when the user clicks on the build button right after creating a new service when the only pending change he has is `project configuration settings`.   The resource type of project configuration settings is filtered out from the build process, that is the reason that in the image below, we can see the commit, but there are no builds.

This is a little bit confusing as the page is called `commits page`, but it actually shows a list of builds of a given (clicked) commit.

The question is if this PR (#3761 ) resolved this issue

You can see that I have the last commit, but I don't have any services:
![image](https://user-images.githubusercontent.com/39680385/189410727-799c12f8-6c4e-4937-ad23-18b2db9c5ff3.png)

**Comment by abrl91** [comment]
fixed by https://github.com/amplication/amplication/pull/3761
