### ISSUE TITLE
🐛 Plugin Event: inconsistent type for updateValues in CreatePackageJson event

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3962]
### What happened?

The type of `updateValues` in `CreateServerPackageJsonParams` is inconsistent with other events that provide the same functionality. 

In other events, we expose an array that allows the plugin writer to push new values to the processes without knowing anything about the current structure or other plugins. Each push is handled separately. 

In the `CreateServerPackageJsonParams`, we expose a single object, which means that one plugin writer can mistakenly overwrite the value provided by previous plugins. 

### CreateServerPackageJsonParams
```
export interface CreateServerPackageJsonParams extends EventParams {
  updateValues: { [key: string]: JsonValue };
}
```

### Other events

```
export interface CreateServerDockerComposeParams extends EventParams {
  fileContent: string;
  updateProperties: { [key: string]: any }[];
  outputFileName: string;
}

export interface CreateServerDockerComposeDBParams extends EventParams {
  fileContent: string;
  updateProperties: { [key: string]: any }[];
  outputFileName: string;
}
```

### What you expected to happen

The type of updateValues should be `updateProperties: { [key: string]: any }[];`

In addition, when changing the type, we should update all plugins that uses this event 

### How to reproduce

n/a

**Comment by yuval-hazaz** [comment]
@arielweinberger I assigned this to you to get your opinion before moving to one of the eng for implementation

**Comment by arielweinberger** [comment]
@yuval-hazaz This is an interesting one. On the one hand, I like the idea of `JsonValue` because it will disallow stuff like functions, so it is more type safe, and feels more appropriate.

On the other hand, `JsonValue` comes from an external package (`type-fest`), which means external plugins will need to have it installed, and I am not a great fan of that.

I'll vote for being consistent and using `{ [key: string]: any }[];`, and I am okay with this change moving to our sprint/backlog.

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4131
