### ISSUE TITLE
🐛 Bug Report: Blocked from creating Message Broker #10

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4008]
I created 10 Message Brokers when I try to create the next one I get this message...

![Image](https://user-images.githubusercontent.com/112330500/193443024-65490bec-5c1d-40ab-a2ec-807e777fee8b.png)

**Comment by saloni137** [comment]
@GreenMachine01 please add more description. I would like to work on this issue

**Comment by yuval-hazaz** [comment]
When you create a message broker, the server auto-generate the name of the resource. 
apparently, after 10 message brokers, the auto-generated name is conflicted with another existing name so we need to fix the code that generate the name

**Comment by souravjain540** [comment]
do you still want to work on it @saloni137

**Comment by kabhamo** [comment]
Hi @GreenMachine01 , @souravjain540 
I hope you are doing great, I would like to take this issue on my own.

After reviewing the code I did not find a function that creates a convenient default name. 
I believe the name was created automatically in the database...

**My idea**
create a function that will check if `resources state` already contains the `ResourceCreateInput.name`.

- If not: it will continue as it should
- else: it will try to create a new convenient name for example in case `resources state` containers  "My message broker-9" and the user wants to create a new message broker the function will update  `ResourceCreateInput.name` to be "My message broker-10" and so on...

Also after I reproduce the bug the website crashed, it is because there is no error handling.
I could add a catch and it will solve the crashing problem.

Please, let me know if you are interested so I can start coding  🚀

This is how it looks without adding an error handler:

![Screenshot 2023-03-08 at 19 24 07](https://user-images.githubusercontent.com/74118584/223785302-4f76ceeb-a1c1-404f-bad8-60f59a82daef.png)

**Comment by souravjain540** [comment]
@GreenMachine01 please see his comment

**Comment by GreenMachine01** [comment]
@abrl91 please see the suggestion from @kabhamo above. if it is approved we can assign the item to him.

**Comment by kabhamo** [comment]
@abrl91 Thanks for the hint and assigning the issue to me.
I will make sure to update my PR.
It will be done this weekend 🚀
