### ISSUE TITLE
🐛 Bug Report: Duplicate label in Topic UI

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#4016]
### What happened?

When creating a topic and giving it a user-friendly name such as "Payment Received", we get two input fields.

- The first input field is the display name, a human-friendly name (in this case, `Payment Received`).
- The second input field is the actual topic name as Kafka sees it. It will become `payment.received`.

Both these fields are currently labeled "Name".

### What you expected to happen

The first field should be labeled "Display Name".
<img width="736" alt="Screenshot 2022-10-02 at 11 31 50" src="https://user-images.githubusercontent.com/4976416/193447656-ed4b4237-51d7-4835-abab-3c9c16241f88.png">
 

### How to reproduce

1. Create a resource of type Message Broker
2. Go to Message Broker
3. Navigate to the "Topics" view on the left-hand nav menu
4. Create a new topic

### Amplication version

1.0.0

**Comment by Ekaji** [comment]
Hi, can i work on this issue?

**Comment by souravjain540** [comment]
> Hi, can i work on this issue?

Assigned. Ask any questions in order to make a PR if needed:)

**Comment by Ekaji** [comment]
unfortunately i have run into some issues setting up this project on my system, as vscode crashes after running ``` npm run setup:dev``` at step 3, please assign the issue to someone else while i figure out whats going on

**Comment by souravjain540** [comment]
> unfortunately i have run into some issues setting up this project on my system, as vscode crashes after running ` npm run setup:dev` at step 3, please assign the issue to someone else while i figure out whats going on

you can ask that in discord server. we would love to help.

**Comment by Utkarsh212** [comment]
@souravjain540, may you assign this issue to me so that I can work on it

**Comment by wiseaidev** [comment]
It looks like an easy issue to grab for me; lemme work on it. But, take a look at how fast my internet connection is:
![Screenshot from 2022-10-07 20-56-07](https://user-images.githubusercontent.com/62179149/194620737-d83c44c0-fb83-4fb8-b250-57a507cdb64e.png)
Blazingly fast!

**Comment by yuval-hazaz** [comment]
> Seems like it's already solved here?

@ranrib see the discussion in #4078

**Comment by Abhay5855** [comment]
@yuval-hazaz I would love to take up this issue can you please assign it to me.Thanks

**Comment by yuval-hazaz** [comment]
sorry @Abhay5855 this issue is already taken

**Comment by souravjain540** [comment]
any updates @wiseaidev

**Comment by wiseaidev** [comment]
Hey @souravjain540, it is fixed by [pull/4078](https://github.com/amplication/amplication/pull/4078). I am not sure about the branching strategy you are following internally, but @barshimi merged it into [branch/4078](https://github.com/amplication/amplication/pull/4127) and then into [branch/next](https://github.com/amplication/amplication/tree/next). So the patch is not reflected on the master branch. You can checkout the next branch to test things out:

```sh
git clone --single-branch --branch next https://github.com/amplication/amplication.git
```
 
Not sure why @barshimi is doing so. It would be nice if someone could elaborate on this matter. Oh wait, that's why my contribution to this repo doesn't show up in this section:

![Screenshot from 2022-10-13 10-30-02](https://user-images.githubusercontent.com/62179149/195531020-42d4e360-7762-4950-a5b8-c1689767a8f6.png)

Ayo! You're a sneaky little so and so.

**Comment by yuval-hazaz** [comment]
@wiseaidev all PRs goes into the `next` branch and will be merged into `master` when we publish the next version to production. because of the holiday season in Israel, we didn't push code to production in a couple of weeks but we will do it soon and you will see all your PRs for Amplication
