### ISSUE TITLE
🐛 Bug Report: Project Configuration is not generated without services

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#4022]
### What happened?

![image](https://user-images.githubusercontent.com/6080188/193448420-86ad4381-3d2d-44fe-9587-aff080f9b932.png)
Project Configuration is not generated without services despite it's shown it pending changes.
This is how commit page looks like after click on build button:
![image](https://user-images.githubusercontent.com/6080188/193448471-91b53caa-241e-458c-905a-b8b79d8e7d78.png)
As wee can see build is broken and doesn't have a status, not successful and not failed.

### What you expected to happen

Three possible solutions: 
1. Generate project configuration anyway
2. Don't show project configuration in pending changes
3. Forbid generating project without services

### How to reproduce

Create Project
Click Build button

**Comment by abrl91** [comment]
The commits page shows the committed services. Every commit can have X builds (as the number of services in the project).
The project configuration (and the MessageBroker) is NOT included in the build process. Therefore, when a user creates a new project and clicks on the build button **before** he creates a service, there is nothing to show on the commits page.

Regarding the pending changes - I agree. It's a bit confusing. I checked what happens when we create a new message broker, and the pending changes remain empty. 

@yuval-hazaz @GreenMachine01 
I am not sure if this setting (base directory) on the project configuration settings page should be reflected somehow in the generated application
![image](https://user-images.githubusercontent.com/39680385/197411630-babd7053-944f-4653-b163-4f6f4a3de455.png)

**Comment by yuval-hazaz** [comment]
The value of this field is currently not being used. We will probably start using it as soon as we start building plugins at the project level like nx support

**Comment by abrl91** [comment]
@yuval-hazaz @GreenMachine01 I'm not sure how to proceed with it

**Comment by GreenMachine01** [comment]
closing due to low value
