### ISSUE TITLE
🐛 Bug Report: Client - Last Commit panel is partially covered by the footer 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#4042]
### What happened?

The Last Commit panel is partially covered by the footer 

<img width="482" alt="image" src="https://user-images.githubusercontent.com/43705455/193746569-2438d27a-95ef-4a45-be25-52f0e9b5402b.png">

### What you expected to happen

The last commit panel should not be covered by the footer 

### How to reproduce

This only happens on a smaller screen when the height is not big enough to include the empty state image (of the box). 
To fix that, we should use a media-query to limit the size of the empty state image on smaller screens (based on the height) or we can just use an image width and height of 120px instead of 150px 

### Amplication version

1.0.2

**Comment by Rutam21** [comment]
@yuval-hazaz I would love to take this up. Please direct me to the file that needs to be worked upon. Thanks.

**Comment by souravjain540** [comment]
@Rutam21 its: `amplication/packages/amplication-client/src/VersionControl/LastCommit.tsx`
assigned.

**Comment by Abhay5855** [comment]
@yuval-hazaz I would love to work on this issue can you please assign it to me

**Comment by Rutam21** [comment]
@Abhay5855 Feel free to work on this and complete your Hacktoberfest campaign. All the best.

**Comment by TheLearneer** [comment]
Hi @yuval-hazaz I would love to work on it if it's available ✋

**Comment by Abhay5855** [comment]
hey Santosh I am working on this issue already

**Comment by souravjain540** [comment]
@Abhay5855 any updates?

**Comment by Abhay5855** [comment]
I have made some changes it is breaking somewhat in the mobile version kindly provide me some time for it I will update you soon

**Comment by yuval-hazaz** [comment]
@Abhay5855 I think we can go with an easy fix and change the image width and height of 120px instead of 150px

**Comment by TheLearneer** [comment]
I would love to work on it, if it is open 🙇

**Comment by souravjain540** [comment]
> I would love to work on it, if it is open 🙇

assigned :)

**Comment by TheLearneer** [comment]
Hi @yuval-hazaz @souravjain540 👋 

So while working on this issue, I have realized that the issue won't be easily fixed by just reducing the image size to 120x120. Screenshot attached for reference
<img width="1440" alt="Screen Shot 2022-10-17 at 9 37 49 PM" src="https://user-images.githubusercontent.com/23402178/196224710-52b5ab22-a72f-4e80-bb71-8b065b5acda4.png">

As you can see in the screenshot, while I open the browser like this in my MacOS, I can't see the `Go to view code` button.

The solutions I can propose are:
1. Add a scrollable container to the entire of the section on the right
2. Also reduce the height of the text area input for commit message from `--textarea-height` to `--textarea-height-small`

I personally feel solution 2 is an easier approach without making any major change, but I can go with either solution you guys feel is better.
I am open to know if there is any other better solutions to it 🙏

**Comment by TheLearneer** [comment]
@abrl91 this is fixed so I believe we are good to close it 🙏

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4187
