### ISSUE TITLE
🐛 Bug Report:  Pending changes aren't updated when renaming the topic name

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4154]
### What happened?

 Pending changes aren't updated when renaming the topic name

https://user-images.githubusercontent.com/39680385/195817290-762fc124-74b7-4ec0-92cd-8e4285acd949.mov

### What you expected to happen

I expect that the topic name on the pending changes will be updated every time the user renames the topic name

### How to reproduce

see the video

### Amplication version

1.0.2

**Comment by MuhammadJufri** [comment]
I would like to work on this if it's available, please

**Comment by abrl91** [comment]
> I would like to work on this if it's available, please

I assigned you. Good luck :)

**Comment by MuhammadJufri** [comment]
Thanks!

**Comment by abrl91** [comment]
@SayyidMuhammad878 Did you manage to make some progress with this issue?

**Comment by SayyidMuhammad878** [comment]
Yes, I was busy I getting a new job I will look after it!

**Comment by SayyidMuhammad878** [comment]
I still working on it but I've completed about 80-90%
Maybe I will push it today or tomorrow

**Comment by MAX-786** [comment]
hey @abrl91, if no one is working on this issue I would like to work on it, can you assign it to me? Thanks :)

**Comment by arielweinberger** [comment]
@SayyidMuhammad878 What do you think? Are we good to wrap this up, or can I assign it to @MAX-786?

**Comment by arielweinberger** [comment]
@MAX-786 I have assinged it to you.

**Comment by MAX-786** [comment]
Thanks @arielweinberger , I will try to create a PR soon

**Comment by SayyidMuhammad878** [comment]
> @MAX-786 I have assinged it to you.

Sorry for late answer, Sure you can assign to MAX-786.
But I have completed 99% only I need to know is which file that invoke the TopicPage file. If there is a file called Abc there is must be another file that called Abc something like this <Abc />

**Comment by MAX-786** [comment]
@arielweinberger if it's not a bother, you can re-assign this issue to @SayyidMuhammad878 since I haven't started working on it. And also while exploring I encountered this design improvement at `/user/profile`  which is :
Before improving,
![Screenshot (28)](https://user-images.githubusercontent.com/99530996/198280664-1c09ad50-6fb2-4ebc-aac7-b16f38f218b2.png)
After improving which I think looks good now,
![Screenshot (27)](https://user-images.githubusercontent.com/99530996/198280895-f181383a-3dca-4c62-b85b-654fa097d775.png)
**Can you please assign this issue to me? Thanks :)**

**Comment by souravjain540** [comment]
assigned to both @SayyidMuhammad878 and @MAX-786  please work on it :)

**Comment by arielweinberger** [comment]
Tested and QA approved.

**Comment by abrl91** [comment]
fixed by  #4928
