### ISSUE TITLE
Investigate increasing developer productivity with pull requests environments

### ISSUE THREAD

**Issue by waveywaves** [amplication/amplication#4176]
### Feature description

I would like to make life easier for Amplification maintainers by implementing [Uffizzi](https://github.com/UffizziCloud/uffizzi) previews. 
Disclaimer: I work on Uffizzi

TODO:

- [ ] Intial POC

### Use case

Uffizzi is a Open Source full stack previews engine and is free for Amplification. This will provide maintainers with previews of PRs made to the Amplification github repo which would be deployed in the cloud. This will allow them to review and get PRs merged faster.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
Thanks for suggesting it. 
I will keep this issue open for @arielweinberger to review it
it may take a couple of weeks before @arielweinberger is back and will be available to review, so please be patient

**Comment by waveywaves** [comment]
Hi @yuval-hazaz 
thanks for getting back. In the meantime, I would like to understand what steps do the maintainers follow to review PRs to Amplification. According to those steps I can figure out how I can shave off steps in your workflow by introducing preview environments for PRs to Amplification.

**Comment by souravjain540** [comment]
@arielweinberger please give your inputs whenever you're available

**Comment by arielweinberger** [comment]
Thank you @waveywaves however we will not be working on this. Here is the reasoning:

1. Uffizzi looks like a very interesting project that can solve this problem for us, but it is very young (138 stars), which would be too early for us to adopt at this point.
2. For us to use this at scale, we would have to pay. Being an open-source project, we favor solutions that have free tiers for open source projects.
3. Perhaps more importantly, we're working on our internal tooling heavily. One of our core initiatives is a better internal developer experience, involving remote environments for testing and preview. Once we are done with this, tackling this issue seems more trivial. This is a far wider DevOps effort.

I'll be closing this for now. Thank you so much for your suggestion, I appreciate that you care about developer experience.

**Comment by waveywaves** [comment]
@arielweinberger we are completely free for open source projects. You wouldn't have to pay, even at your scale. I can create a PoC after which you can see if we fit your needs.

**Comment by arielweinberger** [comment]
Thanks @waveywaves - this is not just about pricing, but as I wrote above, about maturity as well and the fact that we are doing work to improve the way we develop internally (on the cloud), and would like to use the same tooling for preview environments if possible.

If we're able to do this with the same tool, that would make more sense for us to implement. FYI, we're looking into either [https://tilt.dev/](tilt)
