### ISSUE TITLE
🐛 Bug Report: Multiple Services Conflict

### ISSUE THREAD

**Issue by TheDistanceHQ** [amplication/amplication#4316]
### What happened?

I created a 2nd Service for my project, whilst I cloned some assets I left the previous one there.

There is no choice for which Service is then used during compile, in this case it seems to have taken the newer one, which then creates conflicts in the pull requests as they overwrite the same code.

### What you expected to happen

I expected either:

- The services to be stored separately within the folder hierarchy
- Only being allowed to create one service

### How to reproduce

Create a 2nd service in a project and create an identically named asset with different fields

**Comment by TheDistanceHQ** [comment]
I believe this is by design, but I think an extra should be invoked which ensures the folder name or git mapping is confirmed so there aren't file conflicts

**Comment by TheDistanceHQ** [comment]
Probably to be completed as part of:
https://github.com/amplication/amplication/issues/2961

**Comment by yuval-hazaz** [comment]
Thanks @TheDistanceHQ 
I agree about additional validation for the folder name and or git mapping. 
As you said, this behavior is by design to allow you to generate multiple services for the same project, either to different folders in a monorepo or different repos. 

@GreenMachine01 Please include this in one of the next sprints

**Comment by GreenMachine01** [comment]
@yuval-hazaz please define the requested solution.

**Comment by yuval-hazaz** [comment]
@GreenMachine01 it is more of a product solution rather than a technical one. 

It is a matter of validating the value of one service and comparing it with the other services, then either blocking the user or at least showing a warning about the conflict. 

Also, this should be handled in the new Service Creation Wizard, and we can make a smart guess on the needed value based on previous values.
