### ISSUE TITLE
As Dev I want to research solution for our Authentication process

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4484]
Relates to - https://github.com/amplication/amplication-infrastructure/issues/153

- Compare different services or technologies that will be used for our authentication infrastructure including the option to support SSO in the future.
- Alternatively, keep the current infra and just fix the vulnerability (As a temporary solution until SSO)

**Comment by overbit** [comment]
Outcomes: I've summarised the discovery about this on [Notion](https://www.notion.so/amplication/Authentication-Identity-providers-70b78c5db0944fd4bf2b0ba45b294f8b)

I would recommend to focus on the quick fix to start with instead of integrating with an external provider since we are only supporting at this moment GitHub so user will need to have a Github account to integrate with their projects
