### ISSUE TITLE
As Dev - I want to change our strategy of working with Prisma client in the generated app

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4514]
### Feature description

Change our strategy of working with Prisma client in the generated app

related issue: https://github.com/amplication/amplication/issues/4513

- implement the same approach as on Amplication
- create our own Prisma module and use it instead of `nestjs/prisma`
- move the individual Prisma clients from each entity module to the root app module

ADDITIONAL ACCEPTANCE CRITERIA:
- The generated app is built and runs properly on a container - testing locally is not enough!

- [x] #4612
- [ ] #4613

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by tupe12334** [comment]
I agree with the global Prisma client but not about the `nestjs/prisma` one, this package outsources the work with Prisma and nestjs; why do we need this overhead on our side, we have a package that takes the responsibility for that.
What added value its gives us?

**Comment by abrl91** [comment]
@tupe12334 
The idea is to align the app we generate with what we do in Amplication.
We are not using `nestjs-prisma`, we have our own Prisma module and Prisma service in the following way, as NestJS suggest in the documentation:
https://docs.nestjs.com/recipes/prisma#use-prisma-client-in-your-nestjs-services

**Comment by arielweinberger** [comment]
@tupe12334 Look at the link @abrl91 has shared - the `nestjs/prisma` module is not official, and only abstracts one file for you (the Prisma service).

It does not work well in a monorepo setup because it always expects the Prisma client to be at `@prisma/client` and you cannot customize that. For this reason, this abstraction is more pain than gain.

**Comment by yuval-hazaz** [comment]
I think that it is better to provide a more "clear text" and customizable version of the Prisma Service in the generated app to provide the developers with complete control on edge use cases, primarily since this package does not warp a lot of complicated logic and it can be easily replaced with a single service as we do on Amplication server
