### ISSUE TITLE
🐛 Bug Report: invitation link to a workspace doesn't work

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4535]
### What happened?

The invitation link redirects to Amplication but doesn't add the new workspace to the workspace list of the invited user.

Additionally, even after using the invitation link, the user's invitation still appears as "pending".

### What you expected to happen

A user that accepts an invitation should see the new workspace in his workspace list and the link should redirect him to the workspace he was invited to.

The user that sends the invitation shouldn't see that the invitation is still pending.

### How to reproduce

Invite a user to your workspace

### Amplication version

1.0.0

**Comment by EugeneTseitlin** [comment]
@yuval-hazaz @levivannoort  I've reproduced the issue in production, but in dev environment I can't do that because email with invitation was not sent. As far as we have low visibility in production it's hard to understand what went wrong. I suggest configure dev environment to work with AWS SMTP server or deploy SMTP server to our cluster to be able to work on the issue in dev environment. What to you think?

**Comment by yuval-hazaz** [comment]
@EugeneTseitlin, we are using SendGrid to send emails from the server. you should be able to easily create a dev account with send grid and plug in the keys. (we should do it regardless of the current issue)
Also, to test the actual invitation process, you can also copy the invitation code from the DB and create the URL manually

**Comment by abrl91** [comment]
The DSG version is not using the updated version of this fix. I will create a PR to fix it
