### ISSUE TITLE
Mismatched event names

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#4565]
The event names:
- CODE_GENERATION_REQUEST_TOPIC
- CODE_GENERATION_SUCCESS_TOPIC
- CODE_GENERATION_FAILURE_TOPIC

Are not the same between the server and the amplication build manager

**Comment by overbit** [comment]
Would it make more sense to have only 1 topic for these events?

In an event-driven architecture, we should aim to use topic per event instead of actions such as `create-user` `update-user`.

My recommendation would be to have a unique topic, like `code-generation-event` (_naming convention to be reviewed_), and the topic schema like 

```
# event-key
build-id: ""
action: "REQUEST" | "SUCCESS" | "FAILURE" 
```

```
# event-value
input data 
```

**Comment by tupe12334** [comment]
> Would it make more sense to have only 1 topic for these events?
> 
> In an event-driven architecture, we should aim to use topic per event instead of actions such as `create-user` `update-user`.
> 
> My recommendation would be to have a unique topic, like `code-generation-event` (_naming convention to be reviewed_), and the topic schema like
> 
> ```
> # event-key
> build-id: ""
> action: "REQUEST" | "SUCCESS" | "FAILURE" 
> ```
> 
> ```
> # event-value
> input data 
> ```

I agree with you, but this is a separate issue, this one is mandatory for the running of the DSG locally
