### ISSUE TITLE
🐛 Bug Report: Compilation error in the generated app - `Type 'null' is not assignable to type [EntityName]`

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4582]
### What happened?

![image](https://user-images.githubusercontent.com/39680385/206211171-d344c386-57a9-464d-ba75-39f0c18dc8e9.png)

### What you expected to happen

no compilation error

### How to reproduce

- create a project with a service
- sync with GitHub
- clone the generated app
- run:
```bash
cd server && npm i && npm run docker:db && npm run prisma:generate && npm run db:init && npm run start:debug
```
see the errors

### Amplication version

1.1.1

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@abrl91, we need to proceed with fixing this issue. It impacts anyone who creates a service with the lastest version. 

I think the solution would be to update the return type of the function to Promise<Entity[] | null> 
mainly, we need to check the impact of this change and see that there is no code that will break because of this change where it expects to get an empty Array but instead it gets Null now
