### ISSUE TITLE
As Dev - I want to automate DSG deployment for next branch

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#4598]
To simplify the development experience, we are considering updating the DSG tagging strategy as follows:

For `next` environment:
- update CI to add branch name during container tagging
- update next helm values with hardcoded `next` tag

For `staging` environment:
- update CI to add branch name during container tagging (already done as part of next work)
- update next helm values with hardcoded `master` tag

For `production` environment:
- update CI to add `latest` during container tagging
- update next helm values with hardcoded `latest` tag

**Comment by EugeneTseitlin** [comment]
I've tried already to tag by branch name, but for some reason despite that image pull policy was set to always, updated version was not used. I assume that it's related to the fact that sensor is a custom resource.
Anyway, setting production to latest is not a good idea in my opinion. Even if we want use branch tag, production should use master tag.
I suggest to set hash tag as we do it for amplication server.
@overbit @levivannoort @yuval-hazaz What do you think about it?

**Comment by yuval-hazaz** [comment]
One comment from my side- when moving from staging to production, I think we should retag the latest master tag instead of recreating the image from scratch

**Comment by arielweinberger** [comment]
@yuval-hazaz I don't think we should manually do any retagging. Because this only works smoothly when you move from staging to prod immediately without having any commits/pushes in between.

I think we should keep it as it is and let Docker handle the layers cache. If all layers are identical, then AWS ECR will automatically add it as a tag to an existing image.

**Comment by levivannoort** [comment]
Just to add another flavor into the mix. I'd propose that when a new release is created - so we release a tagged version, i.e. v1.2.1 - that that triggers a pipeline that builds the application based of that tag and pushes it with the explicit released version number.

So that our production environments are always identical to the latest public release.

**Comment by levivannoort** [comment]
And as mentioned before, we need to find a workaround argocd image updater as it currently doesnt work in conjuction with the source.type 'plugin', only with vanilla helm & kustomize. Our secret solution that is used via argocd-vault-plugin requires that the 'plugin' type is used however.

I will spend some time this week looking into if there is a way we could use both.

**Comment by overbit** [comment]
> @overbit I like the proposal and exactly what I imagined would work with Docker metadata.
> 
> Aside from latest for master, shall we also add a 'prod' tag?
> 
> What happens in ArgoCD Image Updater is that it takes a tag and looks for differences in the image sha to trigger a redeployment.
> 
> I think using 'prod' for production would make it align with other envs.
> 

@arielweinberger I don't think we would need argocd to retrigger any deployment since we are running jobs that get spin up on demand

**Comment by arielweinberger** [comment]
@overbit ArgoCD Image Updater will need to detect that the image of DSG has been changed, so it can redeploy the sensor specification.

Either way, I think both `latest` and `prod` are good in this case. `prod` to reflect what's actually running in prod (which we aim to correlate with `latest`), and `latest` to semantically indicate the most latest build.
