### ISSUE TITLE
As Dev - I want to research why Webpack is changing the type of objects

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4997]

**Comment by tupe12334** [comment]
The bundling proccess in recreating the class itself, we found a StackOverflow discussion https://stackoverflow.com/questions/48867220/webpack-bundling-library-causing-instanceof-to-fail

**Comment by overbit** [comment]
https://stackoverflow.com/a/41592087/13328183

**Comment by overbit** [comment]
The underline issue of `instanceof` not working properly is due to the two libraries modules having their own copy of the JS file containing the Class constructor, which are both run independently. 
This, in our scenario, is due to webpack bundling the library but it can happen even with npm deep dependencies.

A solution, quite widely accepted and used is to create a new method/property that will be used in the comparison as motionjs does:
https://github.com/moment/moment/blob/e96809208c9d1b1bbe22d605e76985770024de42/src/lib/moment/constructor.js#L78

**Comment by overbit** [comment]
Testing my theory described above is my worst nightmare. Currently we need to publish all the plugins, publish a mod  version of the dsg with an old version of the dependency `prisma-schema-dsl`  before I can use the plugin tester.

**Comment by EugeneTseitlin** [comment]
@overbit Please, link the PR.

**Comment by yuval-hazaz** [comment]
@overbit I reviewed the 2 PRs in  prisma-schema-dsl and prisma-schema-dsl-types

**Comment by overbit** [comment]
In order to test this card, generate some service code using and observe the `prisma.schema`. 
Everything should look good :)
