### ISSUE TITLE
As Operator - I want to be able to release the new "services without authentication" to users without impacting the way they manage/use authentication currently

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5106]
Users should not be aware of or impacted by our refactoring of the authentication.

- [x] Remove auth provider logic from the auth-core plugin 
- [x] Change the event handle server auth to before 
- [x] Create a migration script that will Install once auth-core on all existing resources.

**Comment by morhag90** [comment]
@yuval-hazaz, after rechecking the current behavior, we have the same logic on the existing DSG and the auth-plugin (only that now we need to make sure that the auth-plugin run before the auth-basic/jwt plugin, this is because we are using the same event to implement auth logic). 

The other solution is what we talked about it yesterday: 
Add the auth-X plugin to the default installation list and remove the current logic from the auth-plugin.  

Please tell me what you think :)
