### ISSUE TITLE
🐛 Bug Report: Health Service throws error when mongodb enabled

### ISSUE THREAD

**Issue by MichaelSolati** [amplication/amplication#5362]
### What happened?

With the mongodb plugin enabled the `isDbReady` throws an error preventing the server to start in `server/src/health/base/health.service.base.ts`

### What you expected to happen

Server to work

### How to reproduce

Create a service, enable mongodb, run code locally

### Amplication version

1.4.1

**Comment by tupe12334** [comment]
Prisma is an ORM (Object Relational Mapping) tool that supports multiple databases, including MongoDB. However, Prisma itself does not provide a health check functionality for MongoDB.

To perform a health check for a MongoDB database, you can use the MongoDB driver for Node.js, which Prisma uses under the hood to interact with MongoDB. Here's an example of how to perform a health check using the MongoDB driver:

```typescript
import { MongoClient } = from('mongodb');

const url = 'mongodb://localhost:27017/mydatabase';

async function checkMongoDBHealth() {
  const client = await MongoClient.connect(url, { useUnifiedTopology: true });
  const db = client.db();
  try {
    await db.command({ ping: 1 });
    console.log('MongoDB is running and accepting commands.');
  } finally {
    await client.close();
  }
}

checkMongoDBHealth().catch(error => {
  console.error('Failed to check MongoDB health:', error);
});

```

This code connects to a MongoDB server running on localhost:27017 and sends a ping command to check if the server is running and accepting commands. If the command succeeds, the code logs a message to the console indicating that MongoDB is running and accepting commands. If the command fails, an error is logged to the console.

You can run this code as a separate script or incorporate it into your application code as needed. Note that you'll need to install the mongodb package from npm in order to use the MongoClient class.
