### ISSUE TITLE
🐛 Bug Report: Changing the default selection in the service creation wizard changes the "Continue" button color

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5739]
Might be related to - https://github.com/amplication/amplication/issues/5741

![Image](https://user-images.githubusercontent.com/112330500/230796362-3afdd305-7823-4319-ae08-0534e2ca5bd5.png)

![Image](https://user-images.githubusercontent.com/112330500/230796310-9286832d-c11a-4447-9d68-a62855c502b3.png)

**Expected:**
changing selections on the wizard doesn't impact the button color

**Actual:**
Changing the selection changes the button color from darker purple to a lighter shade

**Comment by yuval-hazaz** [comment]
@GreenMachine01 this happens because the default style of the system, 
the button while on hover or active, has a different color than the normal color. 
so when you change the settings, you actually remove focus from the button.

so, we can either consider resisting the default style, or we can proactively remove the "focus" from the button once the user clicked it.

another option is to use specific style for the button in the wizard

I will let you decide with Alex 
for now, I will lower the priority

**Comment by GreenMachine01** [comment]
@yuval-hazaz @morhag90 
Please remove the "focus" from the button after the user clicks it and is moved to a new/previous step.
from the user perspective its like a new page.

**Comment by jaysoni-ash42** [comment]
@GreenMachine01  can i work on this issue?

**Comment by GreenMachine01** [comment]
@jaysoni-ash42 from my stand point sure take it.
@barshimi can a community member do it or is it a design system issue?
