### ISSUE TITLE
Update Nx to v16 and Storybook v7

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5937]
### Feature description

In order to leverage the latest features and faster build commands, we need to update Nx to the latest version.

#### Tech notes

https://nx.dev/core-features/automate-updating-dependencies#update-to-the-latest-nx-version

**Comment by ognjenjevremovic** [comment]
Hey @overbit I would like to contribute here.  

I already started working on this issue and made some progress, however automatic upgrade (following `nx` migration guide) failed when running `jest` migrations.  
I took some time and ran the migrations manually (in batches), since running all the migrations from a generated `migrations.json` file (generated by `nx cli`) failed for me (multiple times).  

I would require additional input on how to test the changes however. My guess is by running `build`, `test:ci`, `serve:*` would be good first indicatory if the upgrade was successful.  

While on the notes of updates to the latest version of `nx`, are we looking forward to upgrading all the packages in the repository (that `nx` manages like `jest`, `storybook`) or are we interested only in upgrading the `nx` related packages (under `@nx/` scope)?

Thanks in advance! 🚀

**Comment by overbit** [comment]
@ognjenjevremovic are you working on this? If so, I'd assign it to you

**Comment by ognjenjevremovic** [comment]
Hey @overbit apologize for my delayed reply.  
Yes I started working on it and have stumbled a few failed migrations and errors after the upgrade.

I wanted to give it a second try this week; that's why I asked about the approach for testing the upgrade.  
It might take a full week before I get back with any meaningful update on this issue, due to full-time employment. I hope this does not impact the timeline of the rest of the issues.

If slow paced approach is fine, feel free to assign the issue to me 🙂.

**Comment by overbit** [comment]
Completed as part of #7157
