### ISSUE TITLE
As User - I want to sync the code generated by Amplication to AWS CodeCommit

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6351]
**ONLY SERVER**

**Overview:**
We want our platform to support syncing code to AWS CodeCommit. This will broaden our user base by accommodating potential users who are currently using AWS CodeCommit and cannot switch to our platform because we don't yet support it.

This project is identical in essence to what we did with Bitbucket.

**Requirements:**

1. Use Stigg entitlement to control who has access to the AWS CodeCommit capability
2. The platform should be able to authenticate with AWS CodeCommit. This may involve securely storing AWS access keys or using a service like AWS Cognito for authentication.
3. Users should be able to push their code to a specified AWS CodeCommit repository. This will require changes to the code syncing functionality to support the AWS CodeCommit API.
4. The user interface should be updated to provide the option to sync with AWS CodeCommit.
5. Error handling should be robust, and users should be informed if there are issues syncing with AWS CodeCommit. This could involve displaying error messages from the AWS CodeCommit API, or adding our own error handling code.
6. All changes should be thoroughly tested to ensure that they work as expected and do not introduce new issues.
7. Privacy and security implications of storing AWS access keys or other authentication information should be carefully considered.

**Comment by overbit** [comment]
## How to test 

In order to test this, you can use EITHER of the tow following:
1.  call the `createOrganization`  mutation with the user authentication token (taken from the local storage) and the required fields
2.  use the SQL data migration in sandbox available to all engineers here https://start.1password.com/open/i?a=6B76OAHA7NCZTKOAYCLDXWC76I&v=4cicdo4u5rveru347imjpwg4ze&i=rzxcmpvrz6h32japmhbx2j3eb4&h=amplication.1password.com
(Remember to update the workspaceId value)
