### ISSUE TITLE
Entities that were added disappeared after setting permissions

### ISSUE THREAD

**Issue by yam-golombek** [amplication/amplication#671]
I created several entities and they appeared in the Entities table. Afterwards I set permissions and when came back to the Entities table I couldn't find the entities I created - they didn't appear in the table (see screenshot).

![5](https://user-images.githubusercontent.com/71834570/96992200-3663f280-1532-11eb-9157-0122826350af.JPG)

**Comment by yuval-hazaz** [comment]
Thanks @yam-golombek 
Looking at your app I see one additional entity besides the two that appear in your screenshot.
This additional entity was deleted by you and that's why is not in the list.

If you didn't commit the changes, you may be able to see the deleted entity on the pending changes page.
