### ISSUE TITLE
⭐️ Plugin: Auth with 'Supertokens'

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6743]
### Feature description

Allow the code generation with SuperTokens provider

https://supertokens.com/docs/passwordless/nestjs/guide

**Comment by Meyazhagan** [comment]
@overbit I would like to create this plugin. shall I work on this?

**Comment by GreenMachine01** [comment]
![Image](https://github.com/amplication/amplication/assets/112330500/7ac85b6d-b246-420e-a9ac-ece5bf7549d8)

**Comment by d-sonuga** [comment]
Hey @Meyazhagan, I'm already working on this.

**Comment by d-sonuga** [comment]
SuperTokens is an open source Auth0 alternative that can be used for authentication and authorization of users using different authentication methods referred to as recipes.

For information on how SuperTokens works, see [SuperTokens Architecture](https://supertokens.com/docs/passwordless/introduction#architecture).

The way I have decided to approach the development of this plugin is to allow the user to select which SuperTokens recipe they want to use and the plugin will handle the generation of code required to use that recipe.

Because of the role-based authorization scheme that Amplication already generates, I've also decided to use SuperTokens only for authentication and leave the authorization to the Amplication code.

When users sign up or when a new user is created, the SuperTokens core handles the storage of all the user's data, like emails, phone numbers, different login methods, etc. It also generates a unique ID for the user, which the plugin will store in a field called `supertokensId` (or maybe it should be configurable?).

SuperTokens also handles all the session management. When a user is logged in or logs in, the SuperTokens SDK is used to access the user's session.

The user's session contains a lot of useful information like the SuperTokens assigned user ID.

At the moment, the plugin handles authentication by retrieving this SuperTokens assigned user ID from the session and looking up a user in the Amplication DB with an identical value in the `supertokensId` field.

The user found is then determined to be the authenticated user. From then, Amplication's role-based authorization is used to determine whether or not the user has permission to do whatever the user wants to do.

Because of this storing of the `supertokensId` field, additional code is also generated to prevent this field value from going out of sync with the actual value stored on the SuperTokens core.

**Comment by d-sonuga** [comment]
One problem I've encountered while developing this is deciding whether or not to keep some fields, like the username and password field in the user entity.

SuperTokens already stores all of a user's emails and passwords and phone numbers and other user-related info.

At the moment, the plugin keeps the username and password field and uses them to store the email and password of the user.
But in a recipe like passwordless, the user doesn't even have a password. I think that field should be removed.

@overbit, should the username and password fields be removed?
