### ISSUE TITLE
As User - I want build time to be short and stable

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6845]
**Overview:**
Users with very large projects have recently reported experiencing long build times, sometimes exceeding 30 minutes. This can lead to user dissatisfaction, increased support tickets, and potential loss of users to competitors. The aim is to reduce these build times to a more manageable duration and stabilize the build process to minimize failures, thereby improving user satisfaction and retention.

**Requirements:**

1. Research and suggest ways to decrease the build time
2. Research and suggest ways to improve the build stability
3. Implement agreed upon options 

Ideas thread - https://github.com/amplication/amplication/discussions/6747

- [ ] #7327
- [x] #7388
- [x] #7405

**Comment by barshimi** [comment]
There are three point of heavy performance at the DSG. I would suggest two methods of solutions. the first one is a long run solution. This solution will detached all isolated, independent functions and will run them parallel with function wrapper with logger, performance and alert. we can discuss this solution for future changes.

the second solution, which is more doable for the current state of DSG contain:

- run DTO's creation in parallel
- copyFromJobToArtifact (instead of writing file by file, we will write zip or tar once of all files)
- separate or run in parallel server and adminUi
