### ISSUE TITLE
⭐ Plugin: Secret Manager - HashiCorp Vault

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#7014]
As a user, I'd like to use a plugin that will allow to use HashiCorp Vault  for my services.

## Requirements:

- the plugin must modify the  generated `SecretManager` service enabling the user to collect secrets
- the plugin must leverage the supported authentication credentials of `node-vault-client SDK`. If the SDK reads environment variables directly, then a new set of default variables needs to be populated in the `.env` file.
- the must update the generated docker-compose and docker-compose.dev with the new service (`Vault`)
- documentation regarding how the plugin works and, if defined, explain any secrets naming convention used in the plugin

### Settings
- the plugin settings will contain a property `fetchMode` that will allow to collect secrets at start time (`STARTUP`) or at run time (`ON_DEMAND`)

If the user select the option to collect secrets at start-up time (`STARTUP`), the documentation and the plugin settings will need to define a property `secretsNames` that will contain an array of all the secrets that need to be collected during the SecretManager instantiation. 

i.e. `.amplicationrc.json`
```jsonc
// ...
  "settings": {
    "fetchMode": "STARTUP",
    "secretsNames": [
      "/secretA",
      "/path/path2/secretB",
      "/path/path2/path3/secretC"
    ]
  },
// ...
```

## Icon
![HashiCorp Vault](https://github.com/amplication/amplication/assets/112330500/0f8c3797-8cd0-4bb7-9ecc-cb0bce678fa0)

## Prize: USD 250 🏆 

Reply with the proposed solutions and structures.

**Comment by neelshah2409** [comment]
Hey @GreenMachine01 @overbit 
I would like to work on the issue and make the plugin

**Comment by souravjain540** [comment]
> Hey @GreenMachine01 @overbit 
> 
> I would like to work on the issue and make the plugin 

Please share the approach

**Comment by souravjain540** [comment]
@neelshah2409 assigned to you, please dm me on discord and i will add you in a pvt discord channel.

**Comment by souravjain540** [comment]
@neelshah2409 it is mandatory to [join our discord](https://amplication.com/discord) and give updates in the pvt channel.

**Comment by GreenMachine01** [comment]
open to be assigned.

**Comment by easedeath** [comment]
Here is my approach for this problem:

1. Initialize a new repository with the template https://github.com/amplication/plugin-template
2. In the `createServerPackageJSON` `before` event, I will add the `node-vault-client` dependency
3. In the `Create Server Docker Compose` `before` event, I will add the vault docker service (https://hub.docker.com/_/vault/)
4. Since HashiCorp Vault reads the `VAULT_ADDR` env var, i will define it in the event `Create Server Dot Env` `before` that will set the URL that will point to the address where the HashiCorp vault is running
5. Now, for the main plugin impl:
- If the fetch mode is set on startup:
    -  I will secret a new factory that will asynchronous load all the secrets.
    - In the `SecretsManagerService`, i will inject that factory and then override the `getSecret` method to get the related secret
- If the fetch mode is set on demand:
    - In the `SecretsManagerService`, I will override the function `getSecret` that will load the secret from the HashiCorp Vault on demand

Let me know if there is any confusion in my approach.

**Comment by souravjain540** [comment]
@easedeath assigned to you. please join our discord and dm me, i will add you in pvt channel.
