### ISSUE TITLE
🐛 Bug Report:  Tags are not visible For Mobile View

### ISSUE THREAD

**Issue by Prashidha0O1** [amplication/amplication#7195]
### What happened?

In Mobile View, tags are overlapped by the header when displayed in the user interface on the site (https://amplication.com/blog). This behavior is causing a visual inconsistency and may impact the user experience. I am submitting this bug report to bring it to your attention and seek a resolution. 

### What you expected to happen

Tags were not supposed to be superimposed by header content.
![image](https://github.com/amplication/amplication/assets/89299485/7046030a-9421-480e-9708-70e7abde445a)
![image](https://github.com/amplication/amplication/assets/89299485/693e6e5c-656f-4266-8160-f0b63495fb00)
here are these tags.

### How to reproduce

Navigate to this site (https://amplication.com/blog)
open a relevant section where tags are displayed.
Observe that the tags appear to overlap with the header element in the mobile view.

**Comment by Prashidha0O1** [comment]
### Resolve The Issue 
1. Review the HTML and CSS code responsible for rendering tags and headers in the affected section.
2. Use browser developer tools to inspect the elements involved (tags and headers) and identify the specific CSS properties that are causing the overlap.
3. Modify the CSS styles to prevent the overlap. Depending on the specific issue, this may involve changing margins, padding, positioning, or other CSS properties.

**Comment by RitaDee** [comment]
Can I be assigned this?

**Comment by Prashidha0O1** [comment]
@RitaDee yes you can

**Comment by nehasm** [comment]
@RitaDee Can you please assign this bug to me. I've carefully reviewed the issue and have a clear understanding of the problem. The issue primarily pertains to handling padding for screen widths lower than 992px. After conducting a thorough investigation, it's apparent that this issue extends beyond the blog page and affects several pages  across the website. I propose that the fix for this issue will be common and can benefit multiple pages. Also the changes will needed in amplification-site.
