### ISSUE TITLE
🐛 Bug Report: It's not possible to Add Module in custom modules

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7540]
### What happened?

<img width="1253" alt="image" src="https://github.com/amplication/amplication/assets/2861984/ae5de2a7-a77b-4283-a82f-d0a2c1a5fd11">

There is no way for a user to know why it cannot `Add Module` or if it could even.

Related to :
-  #7408

### What you expected to happen

Clicking on `Add Module` to open something or hovering to open a tooltip for the user

### How to reproduce

As enterprise user, create a new project and open the `Modules` tab

### Amplication version

next

**Comment by Meyazhagan** [comment]
I enabled this button and seem it was working. But I saw a couple of issue
- when we are in `All` section, try to `add action` getting `500` error, bcoz moduleId is undefined
- after creating action, in module action form all fields are disable, bcoz `type` is set to `Custom` instead of `actionType`
https://github.com/amplication/amplication/blob/6e7ca45e5ea37c72736d5351ef99757f5de1c0d6/packages/amplication-server/src/core/moduleAction/moduleAction.service.ts#L58

Suggestion,
- By default the path is `/:id/{action-name}`, user should able to modify this path
