### ISSUE TITLE
Improve plugin catalog page UI install / enable UX

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8009]
### Feature description

Currently the UX for installing, enabling/disabling and ordering plugins is not consistent as the user actions required to achieve each action are displayed in different places as shown below:
<img width="1169" alt="image" src="https://github.com/amplication/amplication/assets/2861984/ed957f34-67f5-432c-affb-72d1e450730f">

A more consistent UX will make actions around plugin more natural

**Comment by PazYanoverr** [comment]
Thanks @overbit. 
BTW- When disabling a plugin, it is NOT uninstalled- (1) why?, (2) what does happen when one disables a plugin?
@mulygottlieb

**Comment by yuval-hazaz** [comment]
We do not "uninstall" a plugin because it means that the user will lose any plugin settings. 
we can consider adding "uninstall" but I don't see a reason, at least not a real value that will be enough to prioritize it
Currently, disable acts just like "uninstall" beside the fact that the user can enable it again and getting back all the previous settings if there were any

**Comment by PazYanoverr** [comment]
@yuval-hazaz - Got it. Closing this ticket
