### ISSUE TITLE
Service Catalog: The "Last Build" column should also reflect the status of the last build

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8941]
In the service catalog- the "Last Build" column should be updated to reflect the date of the last build +  the **status** of this build.

This way, on the happy path - the last build is the last successful one.
But, when the last build failed, it will be more important for the user to know that the last build failed rather than what the last successful build was.

Also, the column is clickable, and the user can go into the build log and see the details.

![image](https://github.com/user-attachments/assets/c08bfbaa-69b2-416c-9892-de9dcb769ac3)

**Comment by PazYanoverr** [comment]
@yuval-hazaz @mulygottlieb - FYI

**Comment by yuval-hazaz** [comment]
@PazYanoverr Instead of showing the last successful build, I thought it would make more sense to show the status of the last build

This way, on the happy path - the last build is the last successful one, as you requested. 
But, when the last build failed, I assume it will be more important for the user to know that the last build failed rather than what the last successful build was. 


![Image](https://github.com/user-attachments/assets/deccedef-a153-45e3-8a17-b7d1457f67ee)

**Comment by PazYanoverr** [comment]
@yuval-hazaz - Great, totally makes sense
