### ISSUE TITLE
Template creation wizard- update texts

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8963]
a. Update the text of the following screen to -
         "First, we need to choose a name for the service template"
        " Give your template a meaningful name. The name may include spaces, e.g. ".NET with MSSQL and REST API" 
        "Template name"

![Image](https://github.com/user-attachments/assets/4bd5641d-c394-4df1-815c-c69e73c935a6)

 b. Update the text of the following screen to-
        "How would you like to structure your service template?"
        "Do you want it to include a GraphQL API, REST API, or both? Also, select whether you want to generate the Admin UI for your templated service, with forms to create, update, and delete data."
         The rest should be identical to the "service" version.

![Image](https://github.com/user-attachments/assets/bfa2cba8-58ee-45d4-8e02-59423f5761a0)

 c. Update the following screen to-
         "Which database do you want to use?
          Amplication generates the templated service with all the required configuration and code to start working with a DB. You can easily change the type of DB later on the Plugins page."

![Image](https://github.com/user-attachments/assets/61893a5b-5360-443f-a62c-b6ddfb35d01d)

     
d. Update the text of the following screen to-
         "Your template was created successfully! 🎉
          What should we do next?
          Add plugins to the service template
          I'm done! View my service template

![Image](https://github.com/user-attachments/assets/e31bcc80-0576-4bde-b6c9-f7718093044e)

**Comment by mulygottlieb** [comment]
QA part a - Pass
![Image](https://github.com/user-attachments/assets/50bca0ba-73b2-49b8-9995-eb7229eee804)

QA part b - Pass
![Image](https://github.com/user-attachments/assets/3190e782-6583-44de-b2dd-246c868cf643)

QA part c - Pass
It's missing the word "templated" but I don't think this is a blocker - FYI @PazYanoverr  @yuval-hazaz 
![Image](https://github.com/user-attachments/assets/b7cdb916-a206-46ed-81e0-93de5df026cd)

QA part d - no such part - Pass

QA part e - FAIL - there is a link in the last screen to the template entities - which no longer exist (the definition in the ticket is outdated @PazYanoverr since there are currently no entities, APIs, and Roles on templates)

**Comment by PazYanoverr** [comment]
@mulygottlieb - Good catch! I updated the ticket to reflect the correct behavior

**Comment by mulygottlieb** [comment]
@PazYanoverr @yuval-hazaz , I merged Yuval's PR with all the fixes we discussed, it should be on sandbox soon and then we can continue QA

**Comment by mulygottlieb** [comment]
Re-QA part d - Pass ✅
![Image](https://github.com/user-attachments/assets/a789bc13-bbc7-4766-a0e5-d1d5974149b2)
