### ISSUE TITLE
Allow publish one PP and not all together

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#9081]

**Comment by mulygottlieb** [comment]
Not implemented - re-opening. FYI @yuval-hazaz  @PazYanoverr 
![Image](https://github.com/user-attachments/assets/c2458e78-1b7b-4e05-8cd4-8b145699b95b)

**Comment by mulygottlieb** [comment]
After discussion, it seems the original intention here was to fix the "Publish" button of the Plugin Repository that didn't do anything before, and now it does work.
Since it now works - it passed QA ✅ and I am moving it per that status. I will also rename the ticket title for clarity.

@PazYanoverr  up to you if you think we need to support publishing per PP (and not all PPs together), and if so, open a new ticket for that

**Comment by PazYanoverr** [comment]
https://github.com/amplication/amplication/issues/9145
